roedoejet/g2p

- g2p/mappings/utils.py
see discussion in issue 15 - this patch allows the user to say "word-initial" by setting context_before=`\b`.
> support \b in context_before

- g2p/mappings/__init__.py
`g2p generate-mapping --ipa <lang>` should also output "rule_ordering", not "as_is".
> Fix: generate-mapping should output rule_ordering, not as_is

- g2p/cli.py
Tiny PR, I know, to make `g2p doctor --list-all` output languages in alphabetical order and thus make the output a lot more legible.
> fix(g2p doctor): --list-* options should print langs sorted

- .github/workflows/pythonpublish.yml
- README.md
Currently, the `pythonpublish.yml` workflow is triggered on
- updating the `release` branch
- pushing a tag called `release`
- pushing a tag called `build`
- pushing a tag matching `v*.*.*`
The workflow we want is to publish only when we update the `release` branch, which this PR does.
Also: link to PyPI repo from the README.
> Dev.workflow: update the workflow to only publish from release branch

- .github/workflows/pythonpublish.yml
This PR changes the `pythonpublish.yml` workflow to tag the repo with the version just created automatically.
I tested this reasonably well, in this branch, with a version that echoes the tag command instead of running it. And I tested the tagged process in a different GitHub repo [Just-testing](https://github.com/joanise/just-testing) where I successfully tagged the repo at each commit I pushed in a similar workflow, so I'm fairly confident this will work. But, we'll only know for sure when we do the next g2p release...
Risk: not too much. I put the tag steps at the end, so if it fails, it won't prevent the rest of the workflow from happening. So I think the only risk is that the next release might or might not actually get tagged.
Caveat: it's a bit flaky getting `$VERSION` by parsing …
> Automatically tag the repo on release

- g2p/api.py
Since 2.0.1, flask.blueprint.Blueprint does not accept a "." in the name
of the Blueprint.
FIXES: #111
> fix(deps): make g2p compatible with Flask 2.0.1

- g2p/tests/test_cli.py
- g2p/tests/test_doctor.py
- g2p/tests/test_doctor_expensive.py
For a small drop in code coverage, this PR makes the unit testing suite 20-25s faster.
There were two calls to `g2p doctor` -- one via the CLI, one via the underlying function -- which cost about 25 s together, but did not assert anything useful, so that even a breaking change would probably not have been caught.
So I'm removing these two calls from the test suite: we'll all be happy seeing them run faster, both interactively and in CI.
> Dev.optimize test suites

- .travis.yml
- g2p/mappings/create_fallback_mapping.py
- requirements.txt
Using libraries licensed under the GPL runs of risk of having to consider the whole project GPL. Legal opinions vary on this, but I prefer to play it safe and just never use any GPL-licensed libraries in our code.
This PR does two things:
- Use `text_unidecode` instead of `unidecode`, since the latter is GPL whereas the former is also available under the Artistic License.
- Add a check in our Travis recipe so that a future change that introduces new GPL dependencies will fail to build.
> Dev.no gpl: remove GPL dependencies and prevent future ones.

- g2p/mappings/langs/utils.py
Doh! I should have tested my patch better. As the code now stands, `g2p doctor` does nothing. Revert my changes that broke doctor so that `g2p doctor` runs doctor against all -ipa mappings, as it used it.
Because `g2p doctor` is expensive to run, I previously disabled the unit test that runs it, but I guess that decision came back to byte me today.
> fix(doctor): oops, that last PR broken "g2p doctor" with no argument

- g2p/__init__.py
- g2p/api.py
- g2p/exceptions.py
- g2p/tests/test_network.py
- run_studio.py
- run_tests.py
Change the exceptions raised by `make_g2p()` to NoPath and InvalidLanguageCode instead of NetworkXNoPath and FileNotFoundError.
Rationale:
- the two exceptions are part of the g2p module and can be imported like `from g2p import make_g2p, NoPath, InvalidLanguageCode`
- they're more intuitive (I think)
- and I added documentation on `make_g2p()` with the `Raises:` field so these exceptions are documented as part of the API.
> refactor: make_g2p should raise more meaningful exceptions on caller errors

- Dockerfile
- requirements/requirements.txt
Bump the OS to the current stable, bullseye
Optimize building the docker image
Lock werkzeug to 2.0.3, since our other dependency versions are not compatible with the latest, 2.1.0
> Dockerfile optimizations

- docs/index.rst
- docs/start.rst
- g2p/__init__.py
- g2p/tests/test_api_resources.py
Update the docs with a link to the blog and make a small fix that prevents making a transducer with the same language, i.e. `transducer = make_g2p('alq', 'alq')` throws an exception now whereas before it just caused a nasty 500 error in the API (and the default transducer in the interactive documentation was between 'alq' and 'alq')
> Dev.computel fixes

- README.md
Make the other sources of documentation easier to find without having to actually read the README file.
> docs: add See also section in README.md TOC

- .github/workflows/pythonpublish.yml
- setup.py
According to https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
calling `python setup.py` has been deprecated for a while, and should be
avoided. The recommended replacement is
python -b build --sdist --wheel
which still uses the setup.py file, but in the way that is now considered
correct.  This commits introduces that method. The build command was tested in
ReadAlongs/Studio branch dev.test-build, with the results visible here:
https://github.com/ReadAlongs/Studio/actions?query=branch%3Adev.test-build
Other changes:
- have setup.py declare platform and classifiers
> ci: publish with build instead of calling setup.py directly

- .github/workflows/pythonpublish.yml
- g2p/cli.py
- g2p/mappings/__init__.py
- g2p/tests/public/mappings/gm1-ipa_to_gm2-ipa.json
- g2p/tests/public/mappings/gm2-ipa_to_gm3-ipa.json
- g2p/tests/public/mappings/gm3-ipa_to_gm2-ipa.json
- g2p/tests/test_cli.py
- setup.py
When debugging g2p, I often find I'd like to know what's actually in the cached mappings at a given commit or in a given sandbox. `g2p show-mappings` does just that: dump to screen the stuff that `g2p update` last saved.
Other change: when `context_before` and `context_after` are actually empty, don't print to with `g2p show-mappings` and don't include them in the files generated by `g2p generate-mapping`.
> feat: g2p show-mappings

- g2p/mappings/create_ipa_mapping.py
Long-standing fix I've been intending to do: `g2p generate-mapping --ipa` should also generate mappings with prevent feeding and apply longest first, to avoid bugs in the generated mappings like Shanks and Sabrina discovered in their work.
> fix: generated mappings should prevent feedback and apply-longest-first

- g2p/static/custom.js
The reason und did not work (see issue #165) is that class Transducer
relies on having type == "unidecode" to trigger the und unidecode
processing.
Solution: add an input field for "type", which defaults to "mapping",
but is set to "unidecode" when we load the und->und-ascii mapping from
cache.
Now, that input is really specific, only applicable to the und -> und-ascii
mapping, so hide it and don't let the user play with it.
FIXES #165
> fix: make und work in g2p studio

- .github/workflows/tests.yml
- Dockerfile
- requirements/requirements.dev.txt
It's best practice to update pip to the latest version before using it.
Update our Dockerfiles and tests CI workflow accordingly.
> Update pip before use

- .github/workflows/tests.yml
- g2p/tests/test_mappings.py
Add a second test job in CI to run the test suite on Windows too, since we intend to support Windows.
> Add CI testing on Windows

- .github/workflows/matrix-tests.yml
- g2p/tests/test_mappings.py
Before making a release, let's run the test suite on Windows, MacOS and Ubuntu, with Python versions 3.6 through 3.10.
See https://github.com/roedoejet/g2p/actions/runs/2700305653 for what the action looks like when it fully runs.
> Do full matrix CI on PRs to release

- CITATION.cff
Take advantage if GitHub's citation link in the About section when the citation info existing in a `CITATION.cff` file.
> docs: add CITATION.cff file

- .github/workflows/tests.yml
This is just a minor convenience thing I added to Studio CI workflow as well.
When you're doing work in progress and just want to push a backup on a branch you're planning to throw away, add #no-ci to the commit log and CI gets skipped.
> ci: skip CI tests for commits with #no-ci in the message

- .github/workflows/studio-release-tests.yml
- g2p/app.py
- g2p/exceptions.py
- g2p/mappings/__init__.py
- g2p/mappings/utils.py
- g2p/static/custom.css
- g2p/static/custom.js
- g2p/tests/public/data/__init__.py
- g2p/tests/run.py
- g2p/tests/test_studio.py
- g2p/tests/test_utils.py
- requirements/requirements.test.txt
- run_studio.py
Hey Eric,
This is the PR that will fix https://github.com/roedoejet/g2p/issues/188 among a variety of other undiagnosed issues with haa, mic, tli, ctp, and crk
Basically:
- E2E tests are added for studio that run separately (as they require 3.8)
- G2P Studio was out of date with respect to the `rule_ordering` api
- The "reverse" checkbox should not be checked by default in studio, even if it is in the mapping declaration, because mappings are already reversed when they are sent to the Studio
- We actually had a more general bug in g2p - abbreviations which reference other abbreviations (for example defining `VOWELS` as being comprised of `HIGH_VOWELS` and `LOW_VOWELS` abbreviations was broken. This fixes that by recursively expanding abbreviations (with a fail-safe for self-referential …
> Dev.studio test

- .github/workflows/pythonpublish.yml
- .github/workflows/tests.yml
Fixed:
- actions/codecov-action: bump to v4 uses node16 instead of the deprecated node12
- actions/setup-python: v4 fixes warnings about set-output and save-state being deprecated
- actions/checkout: v3 uses node16 instead of the deprecated node12
Issues not fixed yet, all in `pythonpublish.yml` workflow:
- Out "Determine tag" code gets this warning: Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- mathieudutour/github-tag-action@v5.5 gets the set-output warning and the node12 warning. Update to @v6? https://github.com/mathieudutour/github-tag-action also says to use …
> ci: bump CI actions to current to heed GitHub warnings

- .github/workflows/tests.yml
- g2p/static/custom.css
- g2p/static/custom.js
- g2p/templates/index.html
- add padding at the very bottom, otherwise it looks like you can't scroll to the end of the abbreviations table
- have `convert()` send only non-empty rules and abbreviations to the server, since they just case lots of spurious warnings, and the empty lines in g2p-studio are there to facilitate insert rules, they're not meant to actually be empty rules
- label the first column of the abbreviations table "Abbreviation Name"
- remove the dead `"export-abbs"` listener that depended on the `varhot` variable which got removed a while ago (we now use `$('#export-abbs').click(...)` instead).
Still TODO because I could not figure it out: when you click on EXPORT for either Custom Rules or Custom Abbreviations, rules with an empty `.in` and abbreviations with an empty name should be filtered out …
> Misc improvements to the g2p-studio static app

- g2p/tests/test_unidecode_transducer.py
- g2p/transducer/__init__.py
Fixes to how we sanitize unidecode outputs so that we don't inadvertently throw out the outputs of Han/Kanji unidecoding.  Same changes as the last commit, but on a clean branch.
> Fix to Han/Kanji characters in Und

- g2p/tests/test_unidecode_transducer.py
- g2p/transducer/__init__.py
Fixes to how we sanitize undecode outputs so that we don't inadvertantly throw out the outputs of Han/Kanji unidecoding.  Same changes as the last commit, but on a clean branch.
Pull request template for adding a new language
-----------------------------------------------
*Do not use this for other types of pull requests*
* **Please check if the PR fulfills these requirements**
* **Other information**:
> Fix to Han/Kanji characters in Und Release patch

- requirements/requirements.txt
Tested various versions of networkx to establish compatibility with g2p:
- Python 3.6, which we still support, only has 2.5 and 2.5.1, so >= 2.5 is needed
- networkx 3.0 has a different API than 2.x, so if we were to adopt it, we'd need to modify our code, but then we'd lose support for Python < 3.8, so we don't want to do that now, and we won't want to do it for a while.
- networkx 2.8.5+ work fine, except that the exact contents of g2p/mappings/langs/network.pkl end up slightly different, so then we'd conclude `g2p update` has to be run again, even though the langs DB had not changed.
Thus, I end up with `networkx>=2.5,<=2.8.4`.
What actually happens at the moment of committing:
- Python 3.6: networkx 2.5.1
- Python 3.7: networkx 2.6.3
- Python 3.8-3.10: networkx 2.8.4
- Python 3.11: …
> chore(deps): we are compat with networkx up to 2.8.4

- g2p/api.py
- g2p/cli.py
- g2p/tests/test_cli.py
- g2p/tests/test_indices.py
- g2p/tests/test_lexicon_transducer.py
- g2p/tests/test_tokenize_and_map.py
- g2p/tests/test_transducer.py
- g2p/tests/test_z_local_config.py
- g2p/transducer/__init__.py
This PR extracts the parts of #231 not related to the new web API.  Basically, it:
- Documents the fact that `TransductionGraph` and `CompositeTransductionGraph` have incompatible APIs.
- Uses tuples rather than lists for pairs of (input, output), which should obviously be tuples
- Adds an `alignments` method which consistently returns the input to output indices whether they come from a composed or non-composed graph.
- Adds some other properties and methods that try to regularize the interfaces between similar classes.  If we want to really fix them it will be a breaking change, which I have not done here.
- Adds a `substring_alignments` method which returns the minimal monotonic textual alignments for the transduction edges.  More precisely, in the case where there are crossing …
> Improvements to Transducer API

- g2p/mappings/utils.py
- g2p/tests/public/mappings/hello.aligned.txt
- g2p/tests/test_indices.py
- g2p/tests/test_lexicon_transducer.py
- g2p/tests/test_transducer.py
- g2p/transducer/__init__.py
This fixes a couple of things, actually:
- `substring_alignments` wasn't entirely robust in its handling of deletions (i.e. edges with `None` in second position)
- BUT ... these edges actually never occur with rule-based mappings because `None` is systematically (but somewhat arbitrarily) removed in every case unless there is no output to which a deletion could actually be mapped
- BUT ... it wasn't being systematically removed in some cases (dealing with concatenation) so this fixes that
- AND ... there was a bug in the code that did that which could result in an IndexError so this fixes that too
- and now the lexicon-based mappings handle deletions in the same way as the rules
- and the type annotations indicate where `None` can occur (this could still be improved somewhat)
> fix: handle deletions more consistently in lexicon and rules

- g2p/tests/public/data/__init__.py
- g2p/tests/test_cli.py
- g2p/tests/test_langs.py
Bonus: in VSCode, you can click on that in the logs and it takes you to the test case file directly, from within tests/public/data.
I forgot to PR this change earlier.
> refactor(test): when a mapping fails, show test case filename:lineno

- g2p/__init__.py
Minimal fix for #241.
This whole solution for making utf8 the default on Windows is not elegant in the first, and now I realize even in the readalongs CLI, we rely on `import g2p` to fix the stdout and stderr encoding, which is really not elegant!
This patch should make Bronson's project be able to proceed, but we should review how we make g2p and readalongs handle utf-8 on Windows.
> fix: disable the utf8 fix for windows when running in pytest

- .github/workflows/pythonpublish.yml
Tags should preferably be annotated, so we know who/what created them, and when.
> ci: annotate version tags

- .gitignore
- g2p/__init__.py
- g2p/tests/test_utils.py
get_langs() is now use in both Studio/readalongs and everyvoice, so it belongs upstream in g2p itself, with suitable documentation as to what its output is.
Once this is merged and published, everyvoice and readalongs will be able to get DRYer.
In Studio, though (see branch `dev.factor-out-get_langs` in Studio), we still want to defer loading the g2p database until it's really needed, so we still have a `get_langs()` function that just imports and calls g2p's `get_langs()` function. everyvoice might not need to do the same thing, since it always imports g2p anyway.
> refactor: move get_langs from Studio/readalongs to g2p

- .coveragerc
- .github/workflows/studio-release-tests.yml
- .github/workflows/tests.yml
- g2p/__init__.py
- g2p/_version.py
- g2p/api.py
- g2p/app.py
- g2p/cli.py
- g2p/deprecation.py
- g2p/mappings/create_fallback_mapping.py
- g2p/mappings/tokenizer.py
- g2p/tests/test_check_ipa_arpabet.py
- g2p/tests/test_cli.py
- g2p/tests/test_lexicon_transducer.py
- g2p/tests/test_network.py
- g2p/tests/test_studio.py
- g2p/tests/test_tokenize_and_map.py
- g2p/tests/test_unidecode_transducer.py
- g2p/tests/test_z_local_config.py
- g2p/transducer/__init__.py
Changes the signature of `make_g2p()`: the `tok_lang` argument is now deprecated, tokenization is now the default, and the new name-only arguments `tokenize` and `custom_tokenizer` are now used to select specific behaviours in those corner cases where the default is not right for an app.
Fixes: #252
BREAKING CHANGE: modifies the default behaviour of make_g2p. This is minor, though, and will be a bug fix for most apps, with the exception of ReadAlongs/Studio.
> Change make_g2p to have it tokenize by default

- g2p/mappings/utils.py
- g2p/transducer/__init__.py
Metric: how much RAM this command uses in ReadAlongs Studio:
DEVELOPMENT=1 uvicorn readalongs.web_api:web_api_app --reload
Results:
- baseline: eng lexicon stored as Dict[str, Tuple]       RAM: 100.7 MB
where the tuple value is the parsed alignment
- optimization 1: change to Dict[str, str] where the     RAM:  72.5 MB
str value is the raw alignment string
- failed opt: use a sorted list of tuples                RAM:  75.4 MB
- optimization 2: change to List[str] with k, v          RAM:  61.9 MB
joined by "\0", and bisect_left to find elements
- absolute limit: no lexicon at all (v1.0.20230228)      RAM:  42.9 MB
So the English lexicon required about 60MB RAM in the previous (already optimized!) implementation and now shrinks to about 20MB.
Motivation: this will let us make the ReadAlong …
> perf: optimize lexicon in-memory footprint

- .github/workflows/matrix-tests.yml
- g2p/templates/index.html
- requirements/requirements.txt
- run_studio.py
Python 3.6 is now still supported, but only for the CLI and the g2p library module, but not for g2p Studio.
Dependencies can now be updated as needed for Py >= 3.7 when there are CVEs.
> Adjust dependencies based on the Python version

- requirements/requirements.prod.txt
The Heroku build issues this warning:
DEPRECATION: https://github.com/benoitc/gunicorn/archive/ff58e0c6da83d5520916bc4cc109a529258d76e1.zip#egg=gunicorn==20.1.0 contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617
So use the current "gunicorn @ git:https://..." syntax instead.
And take the latest version of gunicorn while I'm changing this.
> fix: the egg syntax is deprecated, use the at syntax instead

- requirements/requirements.txt
dnspython 2.4.0 drops requests support so we need <=2.3.0 See https://www.dnspython.org/news/2.4.0/
> fix(deps): lock dnspython to compatible 2.3.0

- g2p/tests/public/data/fn_unicode.psv
Indeed, #130 was due to (really annoying) Windows terminal limitations. These extra test cases pass on Windows, confirming it's not a bug in g2p.
> test: add unit test case mimicking #130 to confirm it works on Windows

- g2p/cli.py
- g2p/mappings/.schema/g2p-config-schema-2.0.json
SchemaStore wants the $schema key to be populated, but this is not done by default by pydantic. unfortunately pydantic also targets a different jsonschema dialect than the one recommended by SchemaStore - I'll check to see if this is acceptable.
> feat(schema): update schema generation to include  dialect spec by default

- .github/workflows/tests.yml
We don't run the full matrix on push or PR, only on release, but we should have at least one part of the default CI workflow that runs on every push using Python 3.7, or whatever to minimum required version is when that changes.
> ci: one CI run on push should use the minimum Python, 3.7

- g2p/tests/test_cli.py
If a test CLI fails, then the error message fails also, because we expect the wrong contents in a tuple (we did not notice this because no tests actually fail):
```
======================================================================
FAIL: test_convert (__main__.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/dhd/work/g2p/g2p/tests/test_cli.py", line 148, in test_convert
self.assertEqual(
AssertionError: "Usage: convert [OPTIONS] INPUT_TEXT IN_L[86 chars]ipa)" != 'bɛ̃ː'
+ bɛ̃ː- Usage: convert [OPTIONS] INPUT_TEXT IN_LANG OUT_LANG
- Try 'convert -h' for help.
- 
- Error: Got unexpected extra argument (crg-ipa) : crg-tmd->crg-ipa mapping error for '{first_failed_test[2]}'.
Look for warnings in the log for any …
```
> Fix failure in test failure

- g2p/mappings/langs/utils.py
- g2p/tests/test_cli.py
- requirements/requirements.dev.txt
Turns out that [-1] was there for a reason, there can be arbitrary extra fields (but really just comments) in a test file.  Thanks @joanise  for pointing this out!
> Fix fix to test faliure

- requirements/requirements.dev.txt
This is to fix a kind of annoying gotcha, where you install the package and its dev dependencies, but the tests still can't run.
> build: dev dependencies should include test dependencies

- requirements/requirements.txt
we had locked it to an older version when we were using a flask-socketio that was not compatible with the latest werkzeug, but we bumped that now so we no longer need this, and keeping it makes dependabot unhappy so remove it.
> fix: remove werkzeug lock since it is no longer necessary

- g2p/static/custom.js
CI for da win! It caught the fact that g2p-studio didn't support preserve_case yet.
Tricky case: since preserve_case and case_sensitive are mutually exclusive, I implemented that setting one unsets the other in g2p-studio. Otherwise things just don't work in the studio and the console shows MalformedMapping exceptions that the user would never see.
> g2p-studio also needs to support  preserve_case

- .github/workflows/tests.yml
- g2p/__init__.py
- g2p/cli.py
- g2p/constants.py
- g2p/mappings/create_ipa_mapping.py
- g2p/mappings/langs/__init__.py
- g2p/mappings/tokenizer.py
- g2p/tests/test_indices.py
- g2p/tests/test_studio.py
- g2p/transducer/__init__.py
- g2p/types.py
This is a pretty significant refactoring effort to move all expensive imports out of two places:
- `g2p/__init__.py`: just importing `g2p` should not trigger loading and importing everything
- `g2p/cli.py`: just calling `g2p -h` or `g2p cmd -h` should not trigger loading and importing everything
In both cases, the imports are tucked away inside the functions that need them.
However, we have constants and interfaces we need higher up, so I moved those to a new `g2p/constants.py` file. It's not super elegant, but I think it's at least a partial design improvement: instead of making a top-level module need a deeper one just for its constants or its class definition for typing, I moved them into a lightweight file that both import. This is definitely up for discussion and potential …
> Remove the Flask app from the CLI to speed it up

- g2p/cli.py
- g2p/tests/test_studio.py
This speeds up g2p -h by a couple seconds on my machine.
It continues to bother me that `g2p -h` takes about 7 seconds, now 5 seconds with this PR. It should be sub-second, but it's taking refactoring I don't think we want to do it. However, this small patch is a first step.
> perf: only create APP when it is really needed

- requirements/requirements.txt
See: https://pythonspeed.com/articles/numpy-2
When numpy 2.0.0 is actually out, we'll want to test g2p and our other projects against it before allowing it.
> fix(deps): lock numpy<2 because 2.0.0 is coming and has breaking changes

- g2p/mappings/langs/crj/config-g2p.yaml
- g2p/mappings/langs/crl/config-g2p.yaml
Per community request some months ago.
Result in Studio-Web:
> Move southern and Northern after East Cree to improve sorting

- requirements/requirements.dev.txt
The code is already compliant with that format, but folks will have to redo `pip install -r requirements/requirements.dev.txt` so future code continues to be compliant.
> Move to the current stable black release. 23.x

- docs/package.md
- docs/start.md
g2p.mappings.Rule documentation:
- show the fields in the logical order with "members_order: source"
- show the fields in their normal case rather than all caps with "heading_level: 3" instead of 4
correct a minor detail in the background description of the project.
> docs: minor improvements to g2p manual

- .github/workflows/docs.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/tests.yml
- g2p/_version.py
- g2p/cli.py
- g2p/tests/test_cli.py
- g2p/tests/test_utils.py
- requirements/requirements.test.txt
- setup.py
This is currently "disabled" with the real actions being commented out or prefixed with "echo".
I'd like to test this by pushing an actual test tag, but I want code review before I do it, to make sure I correctly disabled the real work while keeping enough for us to see the result.
> Fully revamp the release workflow, with PEP440 versions and publication triggered by a tag push

- README.md
- docs/migration-2.md
- mkdocs.yml
Migration guide to v2.  Makes it clear enough (I hope) that internal APIs may still be subject to change!
Fixes #325
> Add a basic migration guide to v2

- requirements/requirements.txt
We had locked <=14.0 because 14.1, 14.2, 14.3 and 15.0 were broken for us. 15.0.1 fixes the problem we had.
See https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-15-0-1-2021-06-11
> build(deps): bump coloredlogs to the latest version

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/pythonpublish.yml
There were several bugs that needed fixing in the docs publication workflow.
New model:
- versions get published as, e.g., v2.0, with the latest version getting alias stable, and alias latest as long as no further commits are done on main
- a push to main triggers the update of dev, with alias latest
- the default is stable, so that docs will default to the documentation of the latest version published to PyPI
- https://roedoejet.github.io/g2p/latest will show the latest, typically dev
- https://roedoejet.github.io/g2p/stable and https://roedoejet.github.io/g2p will show the latest stable
- due to limitations in mkdocs-material, the aliases are not shown in the selector, they only work in URLs.
This PR will require a manual push to gh-pages before it's safe to merge, but afterwards docs …
> ci: revamp how we publish documentation

- g2p/mappings/__init__.py
- g2p/mappings/create_ipa_mapping.py
- g2p/tests/test_cli.py
- g2p/tests/test_create_mapping.py
Fixes #353 (do not try to generate mappings for empty symbols)
Fixes #354 (do not copy the rules file name when generating mapping)
> Correct some issues with `g2p generate-mapping`

- .github/workflows/tests.yml
- README.md
- g2p/tests/run.py
- pyproject.toml
All production API code, and API testing code, requires Python 3.7, but the base g2p CLI and library module still support Python 3.7 and need to be testing in CI.
@dhdaines This PR on top of #360 would fix my concerns regarding exercising g2p library tests with Python 3.7
> fix: make the g2p library tests still run on Python 3.7

- .github/workflows/tests.yml
Dependabot does not have permission to post PR comments, but that should not make it fail CI.
> ci: make the PR comment optional so dependabot PRs pass CI

- .github/workflows/tests.yml
- g2p/app.py
- g2p/static/custom.js
One rather important one - we definitely *do not* need to send CORS from the Studio app to accept all origins, this was a (bad) leftover from some example code.  Studio is definitely same-origin and should always be.
One less important one - if you delete all the input, the last character sticks around.  It isn't a problem to request conversion of an empty string so we should allow it to happen.
Also add the G2P_STUDIO_DEBUG environment variable which prints out all the socket.io messages, very useful for debugging.
> A couple of Studio fixes

- .github/pull_request_template.md
- .github/pull_request_template/software_pr.md
Add a software development oriented PR template to this repo.
simple agreement
low
n/a
Since this repo has a default template and an alternative template, it will be a two step process. To see what it will be like, click on https://github.com/joanise/just-testing/compare/main...dev.gzip-on-ci-all-OSs and then manually add `?expand=1&template=studio_web_pr_template.md`, to accurately reproduce the process I'm suggesting for g2p.
high
no
> docs: add a second PR template, for software and other non-mapping PRs

- g2p/mappings/__init__.py
- g2p/tests/test_mappings.py
`as_is` has been deprecated for a long time, but we didn't declare when it would be removed. Let this be that declaration.
Fixes #374
sanity check
low
was already tested
If you want to see it fail, change `version_tuple < (3,):` to `< (2,)`, that will make the as_is unit test fail now, which should get deleted when we release 3.
high
no
> feat: add logic to auto-delete as_is support in g2p 3

- .github/workflows/tests.yml
- g2p/cli.py
- g2p/tests/test_api_resources.py
- g2p/tests/test_cli.py
misc small improvements:
- accept `-` and `/dev/stdin` as stdin (the latter on Linux only)
- when reading a file or stdin, read it and process it line by line - that was just being lazy when I slurped the file up front
- make some unit tests more quiet
standard code review - use SemanticDiff to make it easier to read, though:
https://app.semanticdiff.com/gh/roedoejet/g2p/pull/385
low
yup
- `g2p convert my_file.txt fra fra-ipa` should continue to work as expected, processing the contents of `my_file.txt`
- `echo blah blah | g2p convert - fra fra-ipa` should now work (real use case: replace echo by a meaningful process)
- on Linux only: `g2p convert <(echo blah blah) fra fra-ipa` now also works
The last two cases came up as I was preparing and processing files for EveryVoice, where I wanted …
> Miscenalleous cli improvement for convert

- pyproject.toml
It gives different output and also causes Python 3.8 to crash, as detailed in https://github.com/dmort27/panphon/pull/57
Fixes: #386
> fix(deps): pin panphon to 0.19-0.20 as 0.21 breaks many things

- .github/workflows/pythonpublish.yml
- .github/workflows/tests.yml
Fix the python publish workflow so we can publish 2.1.0
Bug in the workflow that made yesterday's attempt at 2.1.0 fail.
sanity
high
nope
Would require forking and removing the real work from this, so not easily. I'm confident in the patch, but if it breaks again we'll just have to try once more. At least we know nothing goes to PyPI unless everything else succeeds.
High.
yup...
> fix(ci): remove stale job dependency in pythonpublish workflow

- g2p/__init__.py
- g2p/api.py
- g2p/api_v2.py
- g2p/app.py
- g2p/cli.py
- g2p/mappings/langs/__init__.py
- g2p/mappings/langs/network_lite.py
- g2p/mappings/langs/utils.py
- g2p/mappings/tokenizer.py
- g2p/tests/run.py
- g2p/tests/test_network.py
- pyproject.toml
- requirements.txt
Reduce the memory footprint of g2p and RAS API servers, by replacing networkx (~30MB in RAM to import) by the most minimal class that meets the needs of g2p.
Fixes #394
This is pretty core to the library, so careful review of all the code touched by this PR. All testing passes, and I expect coverage to be excellent (yay for our previous test development in this library), so I'm pretty confident it's all good, but still, I'd like careful review.
medium
yup
- `run_tests.py` -> see no failures
- `g2p update` -> see no changes in the generated files
- `g2p convert asdf fra eng-arpabet` -> see the same output as before
- all other g2p operations are affected, so play around if you feel the need, but CI covers it all already, so not really necessary.
medium-high
No. I was careful that it's pure …
> Refactor: replace networkx by a very lightweight custom DiGraph class

- .pre-commit-config.yaml
- g2p/cli.py
- pyproject.toml
Quiet the very verbose warnings that pre-commit gives due to our configuration being in an old format, and improve the presentation for `g2p generate-mapping -h` by formatting indented paragraphs the way markdown expects them.
sanity checking
low
n/a
- make a commit with a pre-commit version 4 installed, and see the absence of warnings
- run `g2p generate-mapping -h` and see the fixed paragraphs formatted correctly, especially on small screens.
high
no
> Two small changes

- docs/package.md
- g2p/__init__.py
- g2p/api_v2.py
- g2p/mappings/tokenizer.py
- g2p/mappings/utils.py
- g2p/shared_types.py
- g2p/tests/test_tokenizer.py
- g2p/tests/test_utils.py
- g2p/transducer/__init__.py
Define a proper class for tokens produced by the g2p tokenizer. Instead of a dict `{"text": "token_text", "is_word": True}`, we now have a `Token` class: `token = Token("token_text", True)`.
Access to the values can be done in the new and old ways:
- `token.text` and `token.is_word` (recommended)
- `token["text"]` and `token["is_word"]` (deprecated, but supported so this PR is not a breaking change)
Additional improvements:
- ~~don't try to install pre-commit 3.2.0 on Python 3.7, it's not available (just don't develop g2p with 3.7, really!)~~ (moved to #408)
- ~~quiet some noisy test suites~~ (moved to #408)
- ~~black some things that should have been blacked before~~ (also #408)
- add more typing, mostly required by the Token refactoring, but also going a little beyond that for things …
> Dev.ej/refactor tokens

- docs/package.md
- g2p/__init__.py
- g2p/api_v2.py
- g2p/mappings/tokenizer.py
- g2p/mappings/utils.py
- g2p/shared_types.py
- g2p/tests/test_tokenizer.py
- g2p/tests/test_utils.py
- g2p/transducer/__init__.py
Introduce the lexicon tokenizer
Fixes #401
This is a draft PR, seeking early feedback on the algorithm I implemented.
medium-high
yes
Run `g2p convert "We'll let go, she'll stop." eng eng-ipa` and see the output `wil lɛt ɡoʊ, ʃil stɑp.` instead of `wi' lɛt ɡoʊ, ʃi' stɑp.`
moderate only.
- unit testing tells me it's fine
- but I have not yet done any benchmarking to see if we need to optimize
Probably yes, at least a patch bump, since this is a bug fix, maybe even a minor bump?
> Dev.ej/lexicon tokenizer

- pyproject.toml
the latest playwright breaks CI for Python 3.8, so hold it back before the version that breaks it.
> ci: fix test-studio to work with Python 3.8

- g2p/app.py
- g2p/static/custom.js
- g2p/templates/index.html
- g2p/tests/test_studio.py
Stabilize testing in CI: test_studio is giving me erratic CI errors, in particular for the changes to kwk, and they are spurious.
This PR makes testing much more stable, and also updates our pre-commit configuration like we've done in ReadAlongs/Studio already.
flaky CI
make sure the updated test_studio makes sense
high, I need to merge this before #418
nothing but!
In one shell: `./run_studio.py`
In another: `g2p/tests/test_studio.py` and see all tests pass, which was the case before, but more importantly see CI pass reliably now.
high
no
> Dev.ej/stabilize test studio in ci

- pyproject.toml
quick fix: click 8.2.0 has breaking changes we're not compatible with, most likely due to incompatibility with other dependencies, likely typer.
Look at the recent Actions runs of Matrix tests, that's where you'll see this patch making a difference, i.e., for Python >=3.10, since click 8.2.0 has dropped <3.10.
> build(deps): lock click<8.2.0 since it has breaking changes
