- g2p/__init__.py
- g2p/transducer.py
- setup.py
Fix a couple of things so that the tests will run under Python 3.6.8 (and change the requirement in setup.py).  Needs testing on Windows!
> python 3.6 compatibility

- g2p/mappings/langs/oji/oji_syllabics_to_orth.csv
> added w final

- .github/pull_request_template.md
- LICENSE
- README.md
- g2p/mappings/langs/atj/config.yaml
- g2p/mappings/langs/crj/config.yaml
- g2p/mappings/langs/crl/config.yaml
- g2p/mappings/langs/crm/config.yaml
- g2p/mappings/langs/csw/config.yaml
- g2p/mappings/langs/win/config.yaml
- Give a more accurate Copyright notice reflecting contributions to this project: AP, DHD, NRC.
- Spell DHD's name correctly everywhere.
Also TODO: change the PR template to add a bullet that reads:
[ ] You agree to license your contribution under the same license as this project (see LICENSE file).
> fix: fix Copyright statements and DHD's name.

- g2p/static/custom.js
Looks like this was a bug from back when we renamed `as_is: true` to `rule_ordering: as-written`. The issue is now fixed.
> fix(studio): fixed config table creation

- g2p/mappings/__init__.py
- g2p/tests/public/mappings/abbreviation_config.yaml
- g2p/tests/public/mappings/abbreviation_mapping.csv
- g2p/tests/public/mappings/abbreviations.substring.csv
- g2p/tests/test_mappings.py
- g2p/tests/test_transducer.py
> fix(mappings): reverse length sort abbreviations to prevent substring errors

- g2p/mappings/langs/__init__.py
- g2p/mappings/utils.py
- g2p/tests/test_mappings.py
- g2p/tests/test_z_local_config.py
- requirements/requirements.prod.txt
another mishmash PR - see individual commit messages
Once this is merged, and a new g2p release is created, I'll be ready to finalize the blog post, referring to that release.
> Dev.ej misc

- g2p/__init__.py
- g2p/mappings/tokenizer.py
- g2p/tests/test_tokenize_and_map.py
- g2p/tests/test_tokenizer.py
Refactors `get_tokenizer` as `make_tokenizer`.
> refactor(tokenizer): refactor to same import strategy as make_g2p

- .github/workflows/pythonpublish.yml
Hard to test until we do the next release, but carefully reviewed.
I suggest we merge this in now, but monitor closely when we make our next release March 1.
> Fix all CI deprecation warnings

- g2p/cli.py
- g2p/mappings/langs/__init__.py
> fix: g2p needs to update both generated .pkl and .json files

- g2p/app.py
- g2p/tests/test_studio.py
coverage made me realize some code in app.py was not actually reachable, and so I did some tweaks around fixing that.
g2p-studio has a small behaviour change: if you set in_lang to eng-arpabet, that used to cause an exception on the back-end and just not update the tables. Now it returns an empty list of mappings and updates the tables to having no tables, since there are no arcs out of eng-arpabet. With that empty list of mappings, the Studio interface basically doesn't map anything anymore and the g2p output box and the animation are basically frozen until you pick a different in_lang. This behaviour ok by me given we haven't got any mappings defined from eng-arpabet.
> refactor: remove dead code in app.py, increase test cov and speed up tests

- .github/workflows/matrix-tests.yml
- g2p/cli.py
- g2p/mappings/__init__.py
- g2p/tests/test_mappings.py
- g2p/transducer/__init__.py
- requirements/requirements.test.txt
Submitted as a new PR on top of yours because I want your feedback on removing the four dunder methods on Mapping before actually doing it.
> final patches on pydantic PR

- g2p/mappings/__init__.py
- g2p/tests/test_mappings.py
fixes: https://github.com/roedoejet/g2p/issues/299
> fix: sort rules without explicit indices

- docs/studio.md
I'm being picky, I know: these are the last changes I would like to see on #333 before merging it.
> docs: polish the g2p-studio option list

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/pythonpublish.yml
Our indentation was inconsistent from one workflow file to another.
I like this guide, 
https://developers.home-assistant.io/docs/documenting/yaml-style-guide/#sequences
which we were already mostly following except for having the list of steps not indented in half the workflows.
> style: apply consistent 2 indent in all ci workflows

- .github/workflows/tests.yml
- g2p/app.py
- g2p/tests/test_studio.py
- run_studio.py
Avoid sending the huge English lexicon over the wire, but recreate it properly in the API.
> Fix lexicon mappings in G2P Studio

- g2p/cli.py
- g2p/tests/test_cli.py
> fix: g2p convert should not add newline when input is a file

- g2p/__init__.py
- g2p/api.py
- g2p/app.py
- g2p/cli.py
- g2p/log.py
- g2p/mappings/create_fallback_mapping.py
- g2p/mappings/create_ipa_mapping.py
- g2p/mappings/langs/__init__.py
- g2p/mappings/langs/utils.py
- g2p/mappings/tokenizer.py
- g2p/tests/test_create_mapping.py
- g2p/tests/time_panphon.py
- g2p/transducer/__init__.py
Some things from `dev.hatch` that do not depend on `hatch`
> Improve coverage and type checking slightly

- g2p/cli.py
significant speed up when using it to process long files.
Fixes: #350
> perf: make g2p convert line-oriented when processing a file

- g2p/api_v2.py
- g2p/app.py
- g2p/tests/run.py
- g2p/tests/test_api_v2.py
- g2p/transducer/__init__.py
- pyproject.toml
Here's the new API used in the alignment demo (https://github.com/dhdaines/alignment-demo and https://aligner.ecolingui.ca/), updated for G2P 2.x.  There's also a small fix to the substring alignment code, can't quite remember what it was for but it should have coverage in any case. (EDIT: Nope actually it doesn't have coverage ... well, that will have to get fixed)
For the moment I made fastapi an optional dependency, so this should have no effect on anything else.  It is based on `dev.hatch` though, at least for the moment.
> API v2, second time around

- .github/workflows/matrix-tests.yml
- .github/workflows/pythonpublish.yml
- g2p/tests/test_tokenize_and_map.py
> Dev.ej/v2.1.0 take3

- g2p/api.py
- g2p/api_v2.py
Set the contact e-mail addresses for both APIs to our team mailing list.
Fixes #372
We agreed to do this 2024-03-24 but I want to make sure that you, @roedoejet and @dhdaines , are still in agreement.
low
> docs: set both API contact e-mails to ras@gmail

- g2p/tests/run.py
- g2p/tests/test_api_v2.py
- g2p/tests/test_cli.py
- g2p/tests/test_indices.py
- g2p/tests/test_lexicon_transducer.py
- g2p/tests/test_tokenizer.py
- pyproject.toml
- run_tests.py
Quiet all test suites - logging should be captured, not allowed to go the screen
Add `--quiet` option to should one `.` per test case instead of the default 1 or 2 lines.
overly verbose test suites
sanity check
low
only tests...
`run_tests.py -h` and play with the options available
high
no
> Dev.ej/refactor test runners

- .github/workflows/tests.yml
Add an automated safeguard against accidental incompatibly licensed dependencies.
Rubber stamping
low
high
no
> ci: run licensecheck to auto-audit our dependencies

- g2p/tests/test_studio.py
Pull request template for adding a new language
-----------------------------------------------
* **Please check if the PR fulfills these requirements**
* **Other information**:
> test: refactor test_studio

- .github/workflows/matrix-tests.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- pyproject.toml
- update the pre-commit config and make it more standard
- fix licensecheck -- needs Python >= 3.9 and adjusted configuration -- this one blocks other PRs since it makes CI fail
- fix a mypy-detected error in app.py
- matrix test more versions
> Fix several repo maintenance issues
